version: "3.9"
services:

  db:
    image: bitnami/postgresql:13.4.0
    container_name: deye-admin_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB}
    ports:
      - '${DOCKER_DATABASE_EXPOSE_PORT}:${DB_PORT}'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB}" ]
      interval: 1s
      timeout: 10s
      retries: 15

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - '${DOCKER_RABBITMQ_EXPOSE_PORT}:${RABBITMQ_PORT}'
      - "${DOCKER_RABBITMQ_UI_EXPOSE_PORT}:${RABBITMQ_UI_PORT}"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}